### ISSUE TITLE
Система статистики

### ISSUE THREAD

**Issue by dmartweb** [unibix/userCMS#106]
Хотелось бы чтобы была система статистики,даже нисколько хиты -хосты ,а своего рода карта кликов,то-есть чтобы в админке показывалось на какие статьи или какие ссылки кликают посетители на сайте.

**Comment by unibix** [comment]
Яндекс.метрика подходит для этого лучше чем что-либо.
И карта кликов (причем тепловая), и карта ссылок, и даже запись поведения пользователя!
И конечно конструктор отчетов в любой удобный вид для вас с любыми фильтрами и датами и целями

**Comment by dmartweb** [comment]
Спасибо,реально лучше так чем грузить систему.
