### ISSUE TITLE
Ошибка sitemap и sitemap xml

### ISSUE THREAD

**Issue by dmartweb** [unibix/userCMS#130]
Когда нажимаешь на действие Управление
Fatal error: Class 'controller_component_core_sitemap' not found in D:\OpenServer\domains\usercms\user_cms\user_cms_core.php on line 208

**Comment by unibix** [comment]
тут тоже нужно перепроверить наследуемый класс для всех компонентов.
и учесть если в компоненте нет Управления (админки) то не выводить что управления нет.
