### ISSUE TITLE
вывод заголовка блока html

### ISSUE THREAD

**Issue by dmartweb** [unibix/userCMS#138]
Добавить опцию для вывода заголовка html блока.

**Comment by unibix** [comment]
что за блок html?

**Comment by dmartweb** [comment]
Ну как же,Блок HTML кода модуль такой

**Comment by unibix** [comment]
так там любой блок можно прописать вообще, да хоть 200 блоков с любым классом

**Comment by dmartweb** [comment]
Ой да точно можно заголовок самому вписать,это только в блоке меню нельзя)

**Comment by unibix** [comment]
закрываем
