### ISSUE TITLE
Баги редактора Jodit

### ISSUE THREAD

**Issue by dmartweb** [unibix/userCMS#139]
1.Если кликнуть рядом с вкладками (Основное,Сео,Вид) и нажать кнопку очистить формат то вкладка форматируется и становится не активной до перезагрузки страницы.
2.С помощью кнопки изменения цвета текста можно изменить текст только один раз, либо цвет текста, либо цвет заливки, и кнопка формата в окне палитры не работает.
3.В блоке custom_html во вкладке параметры не отображаются все кнопки редактора,нужно провернуть страницу вниз чуть чуть тогда появляются

**Comment by unibix** [comment]
Это к автору редактора
