### ISSUE TITLE
Поправить htaccess чтобы работали GET запросы и создавался $_GET

### ISSUE THREAD

**Issue by unibix** [unibix/userCMS#14]
сейчас просто все страницы редиректят на index.php
и передача данных через пост, сессии, куки, или используя:
/param=value/param2=value2
что не всегда удобно, особенно если есть форма с методом гет, то введенные данные не получить, в частности поиск по сайту пока реализован через post, но удобнее будет через get, поскольку при возврате на страницу всплывает окно повторной отправки пост данных

**Comment by vakhrymchuk** [comment]
Так же при методе POST нельзя пошарить ссылку

**Comment by unibix** [comment]
теперь можно.
