### ISSUE TITLE
Slider Cube ошибка удаления

### ISSUE THREAD

**Issue by dmartweb** [unibix/userCMS#151]
не удаляется слайдер

Fatal error: Class 'controller_block_core_cube_slider' not found in D:\OpenServer\domains\usercms.loc\user_cms\modules\components\modules_manager\back_end\controller_component_core_modules_manager.php on line 355

**Comment by unibix** [comment]
зачем удалять? просто деактивируйте. 
Деактивация же нормально проходит?

**Comment by dmartweb** [comment]
Я так полагаю раз есть кнопка Удалить значит она должна удалять)так то можно и из папки удалять модули

**Comment by unibix** [comment]
да, нужно перепроверить удаление ВООБЩЕ ВСЕХ  модулей, точнее переписать наследуемый класс если в модуле это не прописано
